language: python

install:
  - pip install --upgrade pip setuptools tox virtualenv coveralls

script:
  - tox

matrix:
  include:
   - env: TOXENV=py34-django20
     python: 3.4
   - env: TOXENV=py34-django_trunk
     python: 3.4
   - env: TOXENV=py35-django11
     python: 3.5
   - env: TOXENV=py35-django20
     python: 3.5
   - env: TOXENV=py35-django_trunk
     python: 3.5
   - env: TOXENV=py36-django11
     python: 3.6
   - env: TOXENV=py36-django20
     python: 3.6
   - env: TOXENV=py36-django_trunk
     python: 3.6
  allow_failures:
    - env: TOXENV=py34-django_trunk
    - env: TOXENV=py35-django11
    - env: TOXENV=py35-django_trunk
    - env: TOXENV=py36-django_trunk

after_success: coveralls
